services:
  - type: web
    name: java-bot
    env: python
    buildCommand: ""
    startCommand: python3 bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false